---
title: "Session 4"
author: "Abdu"
output:
  html_document:
    df_print: paged
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r , include = TRUE, echo = FALSE, message=FALSE}
library(prettydoc)
library(nycflights13)
library(tidyverse)
library(ggplot2)
df <- head(flights, 10000)
# no need for group by

ggplot(df, aes(x = distance, y = arr_delay, color = carrier)) + 
  geom_point() + 
  labs(x = "Arrival delay", y = "Distance")

```


```{r , include = TRUE, echo = FALSE, message=FALSE}

ggplot(df, aes(x = distance, y = arr_delay, size = air_time)) + 
  geom_point() + 
  labs(x = "Arrival delay", y = "Distance") + 
  theme_bw()

```

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
